### ISSUE TITLE
Sysmods/scripts/indicator-TLP.py

### ISSUE THREAD

**Issue by Offirmo** [silverjam/Sysmods#1]
How do we use it ?
Should I execute it ? Has it dependencies ?

**Comment by silverjam** [comment]
This is a copy of a script referenced on askubuntu, check out the links from the top of the script which explain the deps required:
- http://askubuntu.com/questions/285434/is-there-a-power-saving-application-similar-to-jupiter
- http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html

(_Note: I haven't used this script in a while, so I don't know if it still works_).

Thanks

**Comment by Offirmo** [comment]
I arrived here from the link you give, of course.

However, I couldn't find any explanations on how to install the unity indicator.

**Comment by silverjam** [comment]
You can manually launch it, or add a start-up application to Unity:

https://help.ubuntu.com/16.04/ubuntu-help/startup-applications.html
https://help.ubuntu.com/community/AddingProgramToSessionStartup

Does that help?

**Comment by Offirmo** [comment]
OK so that's a program that must be launched and kept running !

However, it seems it needs some dependencies :

```
Traceback (most recent call last):
  File "./indicator-TLP.py", line 14, in <module>
    import appindicator
ImportError: No module named appindicator
```

I've given up using tlp and switched to cpufrequtils, which has an indicator in apt :-/

**Comment by silverjam** [comment]
Bummer regarding TLP, but glad you found a solution!

**Comment by devken-net** [comment]
I've got the same error.
How can I fix this?

```
$ python indicator-TLP.py
Traceback (most recent call last):
  File "indicator-TLP.py", line 14, in <module>
    import appindicator
ImportError: No module named appindicator

```

**Comment by silverjam** [comment]
Probably can't fix it very easily, as far as I know the indicator-TLP.py script is outdated and broken, you'll have to adapt to whatever is supported on Ubuntu 14.04.

According to this, Ubuntu 12.10 was the last version that had a "appindicator" package:
     https://launchpad.net/ubuntu/trusty/+package/python-appindicator

**Comment by devken-net** [comment]
@silverjam I fixed mine by installing `appindicator` by running

```
sudo apt-get update
sudo apt-get install python-appindicator
```

probably `python-appindicator` is not installed on **Ubuntu 16.04**

**Comment by silverjam** [comment]
Cool, glad it works!
