### ISSUE TITLE
indicator-TLP.py doesn't work with Python 3.x

### ISSUE THREAD

**Issue by pabloab** [silverjam/Sysmods#3]
Comming from [askubuntu](https://askubuntu.com/questions/285434/is-there-a-power-saving-application-similar-to-jupiter), [`indicator-TLP.py`](https://github.com/silverjam/Sysmods/blob/master/scripts/indicator-TLP.py) fist complain about gi, `pip install gi`, then:

    Traceback (most recent call last):
      File "./indicator-TLP.py", line 17, in <module>
        from gi.repository import GObject as gobject
      File "/home/pablo/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
        print url
                ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?

just used Python 2.7 instead of 3 and everything went fine, but would be really great to move to Python 3 compatible source.

**Comment by silverjam** [comment]
The sources are Python 3 compatible, this looks like an error in a dependent library (the `gi` package).

**Comment by silverjam** [comment]
closing issue since it's 3 years old
